# Generated by Django 4.1.4 on 2022-12-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dob',
            field=models.DateField(),
        ),
    ]
