# Generated by Django 4.1.4 on 2022-12-20 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_item_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='DateTime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
